services:
  node0:
    build: .
    command: >
      --id node0
      --addr :8080
      --peers "node1=node1:8080,node2=node2:8080,node3=node3:8080"
      --f 1
    ports:
      - "8080:8080"
    networks:
      - pbft-network

  node1:
    build: .
    command: >
      --id node1
      --addr :8080
      --peers "node0=node0:8080,node2=node2:8080,node3=node3:8080"
      --f 1
    ports:
      - "8081:8080"
    networks:
      - pbft-network

  node2:
    build: .
    command: >
      --id node2
      --addr :8080
      --peers "node0=node0:8080,node1=node1:8080,node3=node3:8080"
      --f 1
    ports:
      - "8082:8080"
    networks:
      - pbft-network

  node3:
    build: .
    command: >
      --id node3
      --addr :8080
      --peers "node0=node0:8080,node1=node1:8080,node2=node2:8080"
      --f 1
    ports:
      - "8083:8080"
    networks:
      - pbft-network

networks:
  pbft-network:
